### ISSUE TITLE
SOA MNAME must not to point at a CNAME or DNAME alias

### ISSUE THREAD

**Issue by pawal** [CENTRccTLDs/TRTF#44] opened 2016-01-15 08:59 UTC
Add test requirement.

**Comment by jschlyter** [comment] 2016-01-18 12:27
ref: RFC2181 section 10.3

**Comment by jschlyter** [comment] 2016-01-18 12:32
Is this a duplicate of #35 ?

**Comment by pawal** [comment] 2016-01-18 13:29
I would say "same same but different". #35 says "FQDN" which just means a complete name (of a name server).

We can combine these by saying that it must resolve to A or AAAA.

**Closed as completed** 2016-01-25 14:30 UTC
Labels: duplicate, MUST, Zone
